//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KursachAdvertasing.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Сustomer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Сustomer()
        {
            this.Advertisement = new HashSet<Advertisement>();
        }
    
        public int IdCustomer { get; set; }
        public string NameCustomer { get; set; }
        public string SurnameCustomer { get; set; }
        public string Phone { get; set; }
        public string EMailCustomer { get; set; }
        public Nullable<int> IdAdvertaisment { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Advertisement> Advertisement { get; set; }
    }
}
